version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
        - postgres-pgadmin.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - devwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
        - postgres-pgadmin.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - devwork

volumes:
  postgres_data:
    external: true
  pgadmin_data:
    external: true

networks:
  devwork:
    external: true
